# List of source files
SRC += $(SRC_DIR)/collision.vhd

# List of test specific simulation files
SRC += tb_collision.vhd

# Top level entity
DUT = collision

# Test duration
STOP_TIME = 10us

# Don't stop on errors
#ASSERT_LEVEL = none

include ../Makefile.inc

