# List of source files
SRC += $(SRC_DIR)/collision_line.vhd
SRC += $(SRC_DIR)/math/adder.vhd
SRC += $(SRC_DIR)/math/dot_product.vhd
SRC += $(SRC_DIR)/math/scalar_product.vhd

# List of test specific simulation files
SRC += tb_collision_line.vhd

# Top level entity
DUT = collision_line

# Test duration
STOP_TIME = 4us

# Don't stop on errors
#ASSERT_LEVEL = none

include ../Makefile.inc

