# List of source files
SRC += ../../synth_mega65r6/mega65/stats.vhd

# List of test specific simulation files
SRC += tb_stats.vhd

# Top level entity
DUT = stats

# Test duration
STOP_TIME = 1us

# Don't stop on errors
#ASSERT_LEVEL = none

include ../Makefile.inc

