# List of source files
SRC += $(SRC_DIR)/math/adder.vhd
SRC += $(SRC_DIR)/math/shifter.vhd
SRC += $(SRC_DIR)/math/unit_vector.vhd

# List of test specific simulation files
SRC += fmt.vhd
SRC += tb_unit_vector.vhd

# Top level entity
DUT = unit_vector

# Test duration
STOP_TIME = 5ms

# Don't stop on errors
#ASSERT_LEVEL = none

include ../Makefile.inc

