# List of source files
SRC += $(SRC_DIR)/ball.vhd
SRC += $(SRC_DIR)/collision_disk.vhd
SRC += $(SRC_DIR)/collision_line.vhd
SRC += $(SRC_DIR)/computer.vhd
SRC += $(SRC_DIR)/math/adder.vhd
SRC += $(SRC_DIR)/math/dot_product.vhd
SRC += $(SRC_DIR)/math/scalar_product.vhd
SRC += $(SRC_DIR)/math/shifter.vhd
SRC += $(SRC_DIR)/math/unit_vector.vhd
SRC += $(SRC_DIR)/player.vhd
SRC += $(SRC_DIR)/score.vhd
SRC += $(SRC_DIR)/sprite_pkg.vhd
SRC += $(SRC_DIR)/tennis.vhd

# List of test specific simulation files
SRC += tb_tennis.vhd

# Top level entity
DUT = tennis

# Test duration
STOP_TIME = 52us

# Don't stop on errors
#ASSERT_LEVEL = none

include ../Makefile.inc

