# List of source files
SRC += $(SRC_DIR)/ball.vhd
SRC += $(SRC_DIR)/collision.vhd
SRC += $(SRC_DIR)/tennis.vhd
SRC += $(SRC_DIR)/sprite_pkg.vhd

# List of test specific simulation files
SRC += tb_tennis.vhd

# Top level entity
DUT = tennis

# Test duration
STOP_TIME = 1us

# Don't stop on errors
#ASSERT_LEVEL = none

include ../Makefile.inc

